### ISSUE TITLE
Implement item class

### ISSUE THREAD

**Issue by adamhl8** [adamhl8/ch4-side-project#10]
We probably want an item class that other more specific types of items can extend (something similar to the Entity class). I'd say just do name for now, I'm not sure what other properties all items would share.

**Comment by kane-droid** [comment]
Sounds good, I start working on it and provide some possibilities for
future implementations in the notes when I push it.

**Comment by kane-droid** [comment]
Sorry, pressed the wrong button.

**Comment by kane-droid** [comment]
Closing due to other ticket fixing this issue.
